server:
  port: 8090
  read_timeout: 30s
  write_timeout: 30s

database:
  host: postgres
  port: 5432
  user: pot_storage_user
  password: pot_storage_secure_pass_2025
  name: pot_storage_db
  ssl_mode: disable

redis:
  host: redis
  port: 6379
  db: 0

storage:
  type: seaweedfs # local 또는 seaweedfs
  local_path: ./uploads
  seaweedfs:
    master_url: seaweedfs-master:9333  # SeaweedFS master server URL

security:
  api_key: pot_storage_api_key_2025 # 초기 인증 키

log:
  level: info